### ISSUE TITLE
Exception thrown when running server

### ISSUE THREAD

**Issue by tnhu** [deepstreamIO/ds-realtime-retrospective-board#1]
I got an exception when running `node start`

```sh
$ node start
      _                     _                              _
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ___   (_) ___
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _ \  | |/ _ \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |_| | (_) |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_(_)_|\___/
                 |_|
 =========================   starting   ==========================
INFO | logger ready
INFO | deepstream version: 2.0.1
INFO | messageConnector ready
INFO | storage ready
INFO | cache ready
INFO | authenticationHandler ready: none
PLUGIN_INITIALIZATION_ERROR | permissionHandler needs to implement isReady or be an emitter
~/workspace/ds-realtime-retrospective-board/server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:28
		throw error;
		^

Error: permissionHandler needs to implement isReady or be an emitter
    at new DependencyInitialiser (~/workspace/ds-realtime-retrospective-board/server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:26:17)
    at Deepstream._start (~/workspace/ds-realtime-retrospective-board/server/node_modules/deepstream.io/src/deepstream.io.js:162:17)
    at g (events.js:286:16)
    at emitNone (events.js:86:13)
    at emit (events.js:185:7)
    at DependencyInitialiser._emitReady (~/workspace/ds-realtime-retrospective-board/server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:113:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
```

**My environments:**

- Mac: 10.11.16
- Node: 6.2.0

**Comment by yasserf** [comment]
Looks like the permission handler is custom and old school, should be valve!  @alex-harley 

Will get fixed asap

**Comment by rajikaimal** [comment]
Still not fixed, gets the same error.

**Comment by yasserf** [comment]
Fixed now

worth mentioning that webRTC is only 1.0 compatible, so that part of the demo won't be working

**Comment by maazsofttech** [comment]
how could it be fixed ...?

**Comment by yasserf** [comment]
> worth mentioning that webRTC is only 1.0 compatible, so that part of the demo won't be working

But you can start the server without it crashing

> Exception thrown when running server
